
server:
  port: 8762
#feign:
#  httpclient:
#    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: manage-order
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&serverTimezone=UTC&allowMultiQueries=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    database: 0
    port: 6379
    jedis:
      pool:
        max-idle: 10
        max-wait: -1
        max-active: 200
        min-idle: 0

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.mr.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true